# Generated by Django 5.1.7 on 2025-03-21 05:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('n_identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('requisitos', models.TextField()),
                ('politicas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('nombre_aeropuerto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especie', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('nombre_aeropuerto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('tarifa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='clientes/')),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_documento', models.CharField(max_length=20)),
                ('n_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeromascotas.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raza', models.CharField(max_length=20)),
                ('especie', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='aeromascotas.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Activa', max_length=20)),
                ('edad', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.IntegerField()),
                ('tamaño', models.CharField(max_length=20)),
                ('inf_medica', models.TextField()),
                ('sexo', models.CharField(max_length=11)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.cliente')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.especie')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.raza')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('vacunas', models.FileField(blank=True, null=True, upload_to='solicitudes/vacunas/')),
                ('informacion_medica', models.FileField(blank=True, null=True, upload_to='solicitudes/medica/')),
                ('certificado_salud', models.FileField(blank=True, null=True, upload_to='solicitudes/certificado/')),
                ('pasaporte', models.FileField(blank=True, null=True, upload_to='solicitudes/pasaporte/')),
                ('documento_cliente', models.FileField(blank=True, null=True, upload_to='solicitudes/documentos_cliente/')),
                ('boleto_vuelo', models.FileField(blank=True, null=True, upload_to='solicitudes/boleto/')),
                ('n_vuelo', models.CharField(blank=True, max_length=20, null=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.administrador')),
                ('aerolinea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.aerolinea')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.cliente')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.destino')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.mascota')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.origen')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.servicio')),
            ],
        ),
    ]
