# Generated by Django 5.1.7 on 2025-03-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeromascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='administradores/'),
        ),
    ]
