# Generated by Django 5.1.7 on 2025-03-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeromascotas', '0003_alter_administrador_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
            ],
        ),
    ]
