# Generated by Django 5.1.7 on 2025-03-26 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeromascotas', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeromascotas.notificacion'),
        ),
    ]
